### ISSUE TITLE
Being pedantic...

### ISSUE THREAD

**Issue by anthonygclark** [paulirish/c-cli#2]
"Terminal"s don't have a cat command, `cat` exists either from the BSD toolset, or GNU coreutils. People confuse a terminal with something other than a `bash` or other shell interpreter. Some commands are `bash` (for example) commands like `read`, `printf`, etc. And some are actual other binaries - i.e., `cat`.

The more you know ...

**Comment by paulirish** [comment]
yah that's fair.

updated the description

:)
